### ISSUE TITLE
Multicalor

### ISSUE THREAD

**Issue by FireSon** [AllexVeldman/esphome-devices#1]
Hi, I am currently working on integrating multical modbus and cane across your repo. Would it be possible to share the https://github.com/AllexVeldman/esphome-multicalor repo as well, since that would probaly be the intresting part :-)

Thanks!

**Comment by AllexVeldman** [comment]
Hi @FireSon, The actual registers used I got from one of the multicalor employees.
They requested me to keep the implementation private back when I built this because they were planning a commercial device at the time.

 I'd love to share the rest and make it fully available, I'll reach out to my contact to see if their stance changed.
I'll let you know!

**Comment by FireSon** [comment]
Hi Alex,

Well the modbus registers I have as well. Just was wondering if you did something smart with them ;-) I have connected my MultiCalor to an airco unit and wanted to manage the ventilator speed. The cooling and heating is a bit too much for the three point speed setting...
I am quite new to EspHome and was wondering if something like the speed control could be easily incorporated.

Regards,
Jan

**Comment by AllexVeldman** [comment]
Nothing special, I do have the fan speed exposed as a [fan component](https://esphome.io/components/fan/index.html) 
<img width="559" alt="image" src="https://github.com/user-attachments/assets/ef16160a-17ac-462b-a760-9075e3291387">

Aside from that I expose some of the registries:
<img width="325" alt="image" src="https://github.com/user-attachments/assets/c4580ad0-6831-4799-97c9-905074167749">

This is the part that connects the modbus components to a HA fan:
```yaml
fan:
  # -- Summer Ventilation Fan
  # Exposed to home assistant.
  # Controls the speed and on/off for the summer ventilation controls.
  - platform: speed
    output: summer_fan_speed
    name: None
    id: my_fan
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - output.turn_on: summer_ventilation_request
    on_turn_off:
    - output.turn_off: summer_ventilation_request
```
where `summer_fan_speed` is the holding registry for the % fan speed and `summer_ventilation_request` is the holding registry for the on/off for the summer ventilation request.
